from __future__ import annotations

PROFILE_DEBIAN = "debian"
PROFILE_UBUNTU_DESKTOP = "ubuntu-desktop"
PROFILE_UBUNTU_SERVER = "ubuntu-server"
PROFILE_KALI_LINUX = "kali-linux"
PROFILE_KALI_PURPLE = "kali-purple"
PROFILE_TAILS = "tails"

PROFILE_KEYS = (
    PROFILE_DEBIAN,
    PROFILE_UBUNTU_DESKTOP,
    PROFILE_UBUNTU_SERVER,
    PROFILE_KALI_LINUX,
    PROFILE_KALI_PURPLE,
    PROFILE_TAILS,
)

WRITE_MODE_DIRECT = "direct"
WRITE_MODE_MANAGED = "managed"

MANAGED_PAYLOAD_LAYOUT_EXTRACTED = "extracted"
MANAGED_PAYLOAD_LAYOUT_RAW_ISO = "raw-iso"
MANAGED_PAYLOAD_LAYOUT_ISO_STORE = "iso-store"
MANAGED_PAYLOAD_LAYOUT_SHARED_DATA = "shared-data"

PERSISTENCE_MODE_NONE = ""
PERSISTENCE_MODE_PLAIN = "plain"
PERSISTENCE_MODE_ENCRYPTED = "encrypted"

PERSISTENCE_MODES = (
    PERSISTENCE_MODE_NONE,
    PERSISTENCE_MODE_PLAIN,
    PERSISTENCE_MODE_ENCRYPTED,
)
